# Labeler configuration for changelog generation
# https://github.com/mikepenz/release-changelog-builder-action

feat:
  - title: 'ğŸš€ Features'
    label: 'feature'
    branch: '.+/feature[/-]'
    match-branch-minor: true

fix:
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
    branch: '.+/fix[/-]'
    match-branch-minor: true

perf:
  - title: 'âš¡ Performance'
    label: 'performance'
    branch: '.+/perf[/-]'

docs:
  - title: 'ğŸ“ Documentation'
    label: 'documentation'

chore:
  - title: 'ğŸ”§ Maintenance'
    label: 'chore'
    branch: '.+/chore[/-]'

refactor:
  - title: 'â™»ï¸ Code Refactoring'
    label: 'refactor'
    branch: '.+/refactor[/-]'

test:
  - title: 'âœ… Testing'
    label: 'test'
    branch: '.+/test[/-]'

ci:
  - title: 'ğŸ‘· CI/CD'
    label: 'ci'
    branch: '.+/ci[/-]'
